type PageField = {
  key: string;
  label: string;
  type?: "text" | "textarea" | "file";
  accept?: string;
  hint?: string;
};

export type PageSettingGroup = {
  group: string;
  label: string;
  fields: PageField[];
};

const heroFields = (prefix: string, defaults: Record<string, string>): PageField[] => [
  { key: `${prefix}_hero_label`, label: "Hero Label" },
  { key: `${prefix}_hero_title`, label: "Hero Title" },
  { key: `${prefix}_hero_highlight`, label: "Hero Highlight (colored text)" },
  { key: `${prefix}_hero_description`, label: "Hero Description", type: "textarea" },
  { key: `${prefix}_hero_cta_primary`, label: "Primary Button Text" },
  { key: `${prefix}_hero_cta_secondary`, label: "Secondary Button Text" },
  { key: `${prefix}_hero_image`, label: "Hero Image", type: "file", accept: "image/*", hint: "Optional background or side image." },
];

export const PAGE_SETTING_GROUPS: PageSettingGroup[] = [
  {
    group: "home_page",
    label: "Home Page",
    fields: [
      { key: "home_hero_badge", label: "Hero Badge Text" },
      { key: "home_hero_line1", label: "Hero Line 1" },
      { key: "home_hero_line1_highlight", label: "Hero Line 1 Highlight" },
      { key: "home_hero_line2", label: "Hero Line 2" },
      { key: "home_hero_line2_highlight", label: "Hero Line 2 Highlight" },
      { key: "home_hero_line3", label: "Hero Line 3" },
      { key: "home_hero_description", label: "Hero Description", type: "textarea" },
      { key: "home_hero_cta_primary", label: "Primary CTA" },
      { key: "home_hero_cta_secondary", label: "Secondary CTA" },
      { key: "home_hero_image", label: "Hero Image", type: "file", accept: "image/*" },
      { key: "home_about_label", label: "About Section Label" },
      { key: "home_about_title", label: "About Section Title" },
      { key: "home_about_highlight", label: "About Section Highlight" },
      { key: "home_industries_label", label: "Industries Label" },
      { key: "home_industries_title", label: "Industries Title" },
      { key: "home_industries_highlight", label: "Industries Highlight" },
      { key: "home_how_label", label: "How It Works Label" },
      { key: "home_how_title", label: "How It Works Title" },
      { key: "home_how_highlight", label: "How It Works Highlight" },
      { key: "home_templates_label", label: "Templates Label" },
      { key: "home_templates_title", label: "Templates Title" },
      { key: "home_templates_highlight", label: "Templates Highlight" },
      { key: "home_pricing_label", label: "Pricing Label" },
      { key: "home_pricing_title", label: "Pricing Title" },
      { key: "home_pricing_highlight", label: "Pricing Highlight" },
      { key: "home_testimonials_label", label: "Testimonials Label" },
      { key: "home_testimonials_title", label: "Testimonials Title" },
      { key: "home_testimonials_highlight", label: "Testimonials Highlight" },
      { key: "home_team_label", label: "Team Section Label" },
      { key: "home_team_title", label: "Team Section Title" },
      { key: "home_team_highlight", label: "Team Section Highlight" },
      { key: "home_faq_label", label: "FAQ Label" },
      { key: "home_faq_title", label: "FAQ Title" },
      { key: "home_faq_highlight", label: "FAQ Highlight" },
      { key: "home_cta_title", label: "Bottom CTA Title" },
      { key: "home_cta_description", label: "Bottom CTA Description", type: "textarea" },
      { key: "home_cta_button", label: "Bottom CTA Button" },
    ],
  },
  {
    group: "about_page",
    label: "About Page",
    fields: [
      ...heroFields("about", {}),
      { key: "about_story_label", label: "Story Section Label" },
      { key: "about_story_title", label: "Story Section Title" },
      { key: "about_story_highlight", label: "Story Section Highlight" },
      { key: "about_story_intro", label: "Story Intro", type: "textarea" },
      { key: "about_values_label", label: "Values Section Label" },
      { key: "about_values_title", label: "Values Section Title" },
      { key: "about_values_highlight", label: "Values Section Highlight" },
    ],
  },
  {
    group: "services_page",
    label: "Services Page",
    fields: heroFields("services", {}),
  },
  {
    group: "team_page",
    label: "Team Page",
    fields: [
      ...heroFields("team", {}),
      { key: "team_leadership_label", label: "Leadership Label" },
      { key: "team_leadership_title", label: "Leadership Title" },
      { key: "team_leadership_highlight", label: "Leadership Highlight" },
      { key: "team_writers_label", label: "Writers Section Label" },
      { key: "team_writers_title", label: "Writers Section Title" },
      { key: "team_writers_highlight", label: "Writers Section Highlight" },
      { key: "team_writers_description", label: "Writers Section Description", type: "textarea" },
    ],
  },
  {
    group: "blog_page",
    label: "Blog Page",
    fields: [
      ...heroFields("blog", {}),
      { key: "blog_search_placeholder", label: "Search Placeholder" },
    ],
  },
  {
    group: "pricing_page",
    label: "Pricing Page",
    fields: [
      ...heroFields("pricing", {}),
      { key: "pricing_faq_label", label: "FAQ Section Label" },
      { key: "pricing_faq_title", label: "FAQ Section Title" },
      { key: "pricing_faq_highlight", label: "FAQ Section Highlight" },
    ],
  },
  {
    group: "templates_page",
    label: "Templates Page",
    fields: heroFields("templates", {}),
  },
  {
    group: "get_started_page",
    label: "Get Started Page",
    fields: [
      { key: "get_started_label", label: "Page Label" },
      { key: "get_started_title", label: "Page Title" },
      { key: "get_started_highlight", label: "Title Highlight" },
      { key: "get_started_description", label: "Page Description", type: "textarea" },
    ],
  },
];

export const PAGE_CONTENT_DEFAULTS: Record<string, string> = {
  home_hero_badge: "✦ ATS-Optimized Resumes",
  home_hero_line1: "Land Your",
  home_hero_line1_highlight: "Dream Job",
  home_hero_line2: "with a",
  home_hero_line2_highlight: "Winning",
  home_hero_line3: "Resume",
  home_hero_description: "Professional resume writers crafting career stories that get noticed. ATS-optimized, industry-tailored, and designed to get you interviews.",
  home_hero_cta_primary: "✦ Get My Resume Written",
  home_hero_cta_secondary: "View Samples",
  home_about_label: "About ProCareerVista",
  home_about_title: "We Don't Just Write Resumes — We Build",
  home_about_highlight: "Career Stories",
  home_industries_label: "Industries We Serve",
  home_industries_title: "Specialists Across",
  home_industries_highlight: "Every Sector",
  home_how_label: "How It Works",
  home_how_title: "Start Your Journey in",
  home_how_highlight: "3 Simple Steps",
  home_templates_label: "Resume Templates",
  home_templates_title: "Designs That",
  home_templates_highlight: "Get Noticed",
  home_pricing_label: "Transparent Pricing",
  home_pricing_title: "Choose Your",
  home_pricing_highlight: "Career Plan",
  home_testimonials_label: "Client Reviews",
  home_testimonials_title: "What Our Clients",
  home_testimonials_highlight: "Are Saying",
  home_team_label: "Meet the Team",
  home_team_title: "The",
  home_team_highlight: "Experts Behind Your Success",
  home_faq_label: "Frequently Asked",
  home_faq_title: "Got",
  home_faq_highlight: "Questions?",
  home_cta_title: "Ready to Transform Your Career?",
  home_cta_description: "Join 12,000+ professionals who landed their dream jobs with ProCareerVista.",
  home_cta_button: "✦ Get Started Today",
  about_hero_label: "Our Story",
  about_hero_title: "We Believe Every Professional Deserves",
  about_hero_highlight: "to Be Seen",
  about_hero_description: "Founded in 2015, ProCareerVista has helped over 12,000 professionals across 45 countries land their dream jobs through the power of strategic career storytelling.",
  about_hero_cta_primary: "✦ Start Your Journey",
  about_hero_cta_secondary: "Meet Our Team",
  about_story_label: "Our Journey",
  about_story_title: "A Decade of Transforming Careers",
  about_story_highlight: "Transforming Careers",
  about_story_intro: "What started as a small freelance operation in a home office has grown into a full-service career consultancy trusted by professionals across the globe.",
  about_values_label: "Our Values",
  about_values_title: "What We Stand For",
  about_values_highlight: "Stand For",
  services_hero_label: "What We Offer",
  services_hero_title: "Every Service You Need to",
  services_hero_highlight: "Land Your Dream Job",
  services_hero_description: "From resume rewrites to interview coaching — we offer a complete suite of career services to give you a decisive competitive edge.",
  services_hero_cta_primary: "✦ Get Started",
  services_hero_cta_secondary: "View Pricing",
  team_hero_label: "Meet the Experts",
  team_hero_title: "The People Behind",
  team_hero_highlight: "Your Success",
  team_hero_description: "Our team of certified resume writers, career coaches, and ATS specialists are dedicated to one mission: getting you hired.",
  team_hero_cta_primary: "✦ Work With Our Team",
  team_leadership_label: "Leadership",
  team_leadership_title: "Our",
  team_leadership_highlight: "Founding Team",
  team_writers_label: "Our Writers & Specialists",
  team_writers_title: "Our Full",
  team_writers_highlight: "Team of Experts",
  team_writers_description: "Every ProCareerVista writer holds active CPRW certification and specializes in specific industry verticals.",
  blog_hero_label: "Career Insights",
  blog_hero_title: "The ProCareerVista",
  blog_hero_highlight: "Career Blog",
  blog_hero_description: "Expert advice on resume writing, job searching, LinkedIn strategy, and career growth — published weekly by our certified writers and career coaches.",
  blog_search_placeholder: "Search articles, tips, guides...",
  pricing_hero_label: "Simple, Transparent Pricing",
  pricing_hero_title: "Invest in Your",
  pricing_hero_highlight: "Career Future",
  pricing_hero_description: "One-time payments. No subscriptions. Every plan includes our 30-day money-back guarantee and unlimited revisions until you're 100% satisfied.",
  pricing_hero_cta_primary: "✦ Get Started Now",
  pricing_hero_cta_secondary: "Compare Plans",
  pricing_faq_label: "Common Questions",
  pricing_faq_title: "Pricing FAQs",
  pricing_faq_highlight: "FAQs",
  templates_hero_label: "Resume Templates",
  templates_hero_title: "Professional Templates",
  templates_hero_highlight: "That Get Interviews",
  templates_hero_description: "Browse our collection of ATS-optimized resume templates — designed by career experts and trusted by thousands of professionals.",
  templates_hero_cta_primary: "✦ Get Started",
  templates_hero_cta_secondary: "View Pricing",
  get_started_label: "Start Your Order",
  get_started_title: "Let's Build Your",
  get_started_highlight: "Winning Resume",
  get_started_description: "Complete the form below — it takes about 5 minutes. Your assigned writer will be in touch within 2 hours.",
};

export const IMAGE_SETTING_KEYS = new Set(
  PAGE_SETTING_GROUPS.flatMap((g) => g.fields.filter((f) => f.type === "file").map((f) => f.key))
);

IMAGE_SETTING_KEYS.add("site_logo");
IMAGE_SETTING_KEYS.add("favicon");
